<?php

/**
 * Created by PhpStorm.
 * User: Thijs van der Poel
 * Date: 18/11/2019
 */
/*
 * Template Name: EHBO Hulst Contact
 * Description: Deze template is voor uw contact pagina
 */
get_header();


?>
<!--CONTENT-->
<div class="content">

    <!--INNER CONTENT-->
    <div class="inner-content grid-x grid-margin-x ">

        <!--MAIN GRID SECTION-->
        <main class="main small-12 medium-12 large-12 cell" role="main">

            <!--HEIGHT SPACER-->
            <div class="spacer"></div>

            <!--INFO ROW-->
            <div class="grid-x">

                <!--SPACER COLUMN-->
                <div class="cell small-1 medium-1 large-2">
                </div>

                <!--CONTACT BLOCK-->
                <div class="contactForm cell small-12 medium-10 large-8">
                    <h5 class="contactHeader">Contact</h5>
                    <?php
                    //Loading of a shortcode for the Contact Form 7 plug-in, with an ID generated by this plug-in.
                    echo do_shortcode('[contact-form-7 id="61" title="Contactformulier"]');
                    ?>
                </div>

                <!--SPACER COLUMN-->
                <div class="cell small-1 medium-1 large-2">
                </div>

            </div> <!-- end #info row -->

            <div class="grid-x">
                <!--SPACER COLUMN-->
                <div class="cell small-1 medium-1 large-2">
                </div>

                <div id="lowerContactSlant" class="contactForm cell small-12 medium-10 large-8"></div>

                <!--SPACER COLUMN-->
                <div class="cell small-1 medium-1 large-2">
                </div>
            </div>

        </main> <!-- end #main -->
    </div> <!-- end #inner-content -->

    <!--HEIGHT SPACER-->
    <div class="spacer"></div>

</div> <!-- end #content -->


<!--FOOTER-->
<div class="show-for-large">
    <?php
    get_footer();
    ?>
</div>
